require('plugins')
require('keybindings')
require('options')
require('nvim-tree-config')
require('lualine-config')
require('bufferline-config')
require('treesitter-config')
require('autopairs-config')
require('whichkey-config')
require('telescope-config')
require('colorizer-config')
require('dashboard-config')
require('blankline-config')
require('format-config')
require('toggleterm-config')
require('comment-config')
require('theme-config')
require('zen-mode-config')
require('twilight-config')
require('transparent-config')
require('numToStr-comment-config')
require('commentstring-config')
require('null-ls-config')
require('lsp')


